FROM node:12.0.0-alpine

WORKDIR '/app'

# Install yarn and other dependencies via apk
RUN apk update && apk add yarn python g++ make && rm -rf /var/cache/apk/*

COPY package.json yarn.lock /app/

RUN npm install
RUN yarn global add react-scripts
RUN npm install --save react react-dom
COPY . ./


CMD ["yarn", "start"]